print("+{:-<5}+ {:-^20}+ {:->12} +".format("", "", ""))
print("|{:<5}| {:^20}| {:>13} +".format("ID", "Ho va ten", "Noi sinh"))
print("|{:<5}| {:^20}| {:>13} +".format("123", "Yui Hatano", "Japanese"))
print("|{:<5}| {:^20}| {:>13} +".format("6969", "Sunny Leone", "Canada"))
print("+{:-<5}+ {:-^20}+ {:->12} +".format("", "", ""))
